// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop_Manager.DbContext;

#nullable disable

namespace Shop_Sales.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    partial class ShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("Shop_Manager.Models.DriverTrip", b =>
                {
                    b.Property<int>("trip_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("departure_time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("employee_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("region_id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("shiftPay_in_cents")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("trip_id");

                    b.HasIndex("employee_id");

                    b.HasIndex("region_id");

                    b.ToTable("Driver_Trip");
                });

            modelBuilder.Entity("Shop_Manager.Models.Employee", b =>
                {
                    b.Property<int>("employee_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("hourlyPay_in_cents")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("shiftPay_in_cents")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("employee_id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Shop_Manager.Models.EmployeeShift", b =>
                {
                    b.Property<int>("shift_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("employee_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("end_time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("start_time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("shift_id");

                    b.HasIndex("employee_id");

                    b.ToTable("Employee_Shift");
                });

            modelBuilder.Entity("Shop_Manager.Models.Records", b =>
                {
                    b.Property<int>("record_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("amount_in_cents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("record_id");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("Shop_Manager.Models.Region", b =>
                {
                    b.Property<int>("region_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("fee_in_cents")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("region_id");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("Shop_Manager.Models.DriverTrip", b =>
                {
                    b.HasOne("Shop_Manager.Models.Employee", "employee")
                        .WithMany()
                        .HasForeignKey("employee_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop_Manager.Models.Region", "region")
                        .WithMany()
                        .HasForeignKey("region_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");

                    b.Navigation("region");
                });

            modelBuilder.Entity("Shop_Manager.Models.EmployeeShift", b =>
                {
                    b.HasOne("Shop_Manager.Models.Employee", "employee")
                        .WithMany()
                        .HasForeignKey("employee_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");
                });
#pragma warning restore 612, 618
        }
    }
}
